debug: false
listenAddr : "0.0.0.0:3000" 
staticDir: "./static"
templateDir: "./templates"
allowOrigins:
  - "http://localhost:8080"

session:
  cookieName: "sid"
  cookieSecure: false
  cookieMaxAge: false
  cookieHttpOnly: true
  storageKeyPrefix: "cas:sid:"
  redisUrl: redis://<user>:<pass>@localhost:6379/<db>

database:
  dataSourceName: user:password@tcp(localhost:3306)/cas?charset=utf8mb4&parseTime=True&loc=Local
  maxIdleConns: 10
  maxOpenConns: 10
  connMaxIdleTime: 10
  connMaxLifetime: 10

redis: 
  enabled: true
  url: redis://<user>:<pass>@localhost:6379/<db>

oauth: 
  google:
    clientId: xxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com
    clientSecret: xxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxxx
