debug: false

server:
  listenAddr : "0.0.0.0:3000" 
  staticDir: "./static"
  templateDir: "./templates"
  allowOrigins:
    - "http://localhost:8080"

database:
  dataSourceName: user:password@tcp(localhost:3306)/cas?charset=utf8mb4&parseTime=True&loc=Local
  maxIdleConns: 10
  maxOpenConns: 10
  connMaxIdleTime: 10
  connMaxLifetime: 10

oauth: 
  google:
    clientId: xxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com
    clientSecret: xxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxxx
