
// Code generated by /tmp/go-build3518660525/b001/exe/main DO NOT EDIT.

package query

// Columns of User
const ColUserID = "id"
const ColUserCreatedAt = "created_at"
const ColUserUpdatedAt = "updated_at"
const ColUserDeletedAt = "deleted_at"
const ColUserName = "name"
const ColUserDisplayName = "display_name"
const ColUserEmail = "email"
const ColUserEmailVerified = "email_verified"
const ColUserPassword = "password"
const ColUserDisabled = "disabled"
const ColUserLastLoginAt = "last_login_at"
const ColUserOAuths = "oauths"

// Columns of UserOAuth
const ColUserOAuthID = "id"
const ColUserOAuthCreatedAt = "created_at"
const ColUserOAuthUpdatedAt = "updated_at"
const ColUserOAuthDeletedAt = "deleted_at"
const ColUserOAuthOAuthId = "oauth_id"
const ColUserOAuthUserId = "user_id"
const ColUserOAuthProvider = "provider"
const ColUserOAuthEmail = "email"
const ColUserOAuthName = "name"
const ColUserOAuthPicture = "picture"

// Columns of Service
const ColServiceID = "id"
const ColServiceCreatedAt = "created_at"
const ColServiceUpdatedAt = "updated_at"
const ColServiceDeletedAt = "deleted_at"
const ColServiceDisplayName = "display_name"
const ColServiceClientId = "client_id"
const ColServiceClientSecret = "client_secret"
const ColServiceServiceUrl = "service_url"
const ColServiceCallbackUrl = "callback_url"
const ColServiceAutoLogin = "auto_login"

// Columns of Token
const ColTokenID = "id"
const ColTokenCreatedAt = "created_at"
const ColTokenUpdatedAt = "updated_at"
const ColTokenDeletedAt = "deleted_at"
const ColTokenCode = "code"
const ColTokenUser = "user"
const ColTokenRealm = "realm"
const ColTokenAccessToken = "access_token"
const ColTokenRefreshToken = "refresh_token"
const ColTokenScope = "scope"
const ColTokenExpireIn = "expire_in"
const ColTokenType = "type"
const ColTokenRevoked = "revoked"
