
// Code generated by /tmp/go-build2687635491/b001/exe/main DO NOT EDIT.

package query

// Columns of Realm
const ColRealmID = "id"
const ColRealmCreatedAt = "created_at"
const ColRealmUpdatedAt = "updated_at"
const ColRealmDeletedAt = "deleted_at"
const ColRealmName = "name"
const ColRealmDisplayName = "display_name"

// Columns of User
const ColUserID = "id"
const ColUserCreatedAt = "created_at"
const ColUserUpdatedAt = "updated_at"
const ColUserDeletedAt = "deleted_at"
const ColUserUsername = "username"
const ColUserDisplayName = "display_name"
const ColUserEmail = "email"
const ColUserEmailVerified = "email_verified"
const ColUserPassword = "password"
const ColUserDisabled = "disabled"
const ColUserLastLoginAt = "last_login_at"

// Columns of Service
const ColServiceID = "id"
const ColServiceCreatedAt = "created_at"
const ColServiceUpdatedAt = "updated_at"
const ColServiceDeletedAt = "deleted_at"
const ColServiceDisplayName = "display_name"
const ColServiceClientId = "client_id"
const ColServiceClientSecret = "client_secret"
const ColServiceServiceUrl = "service_url"
const ColServiceCallbackUrl = "callback_url"

// Columns of Token
const ColTokenID = "id"
const ColTokenCreatedAt = "created_at"
const ColTokenUpdatedAt = "updated_at"
const ColTokenDeletedAt = "deleted_at"
const ColTokenCode = "code"
const ColTokenUser = "user"
const ColTokenRealm = "realm"
const ColTokenAccessToken = "access_token"
const ColTokenRefreshToken = "refresh_token"
const ColTokenScope = "scope"
const ColTokenExpireIn = "expire_in"
const ColTokenType = "type"
const ColTokenRevoked = "revoked"
